name = "mycelia-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "359bbec67c35603c232096900443f5f5"

[observability]
enabled = true

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "mycelia-db"
database_id = "2d0fcc8f-388d-438f-84de-fa819b67a929"

[[kv_namespaces]]
binding = "KV"
id = "4be87b971aa44128a9f2cdeccd4306b8"


# Cron trigger for timeouts/expiry
[triggers]
crons = ["*/15 * * * *"]
